# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [31]:
import numpy as np
from sklearn. preprocessing import normalize

arr = np.random.randint(0, 21, size = 28).reshape(4, 7)
def normalize_array(arr):
    min_value = np.min(arr)
    max_value = np.max(arr)
    a = 1 / (max_value - min_value)
    b = -min_value / (max_value - min_value)
    
    normalized_arr = a * (arr - min_value) + b
    
    return normalized_arr

print(normalize_array(arr))
normalizedData = (arr-np.min(arr))/(np.max(arr)-np.min(arr))
print(normalizedData)
distance = np.linalg.norm(arr)
print(distance)

[[ 0.42105263  0.15789474  0.10526316  0.73684211  0.68421053  0.73684211
   0.05263158]
 [ 0.05263158  0.26315789  0.10526316  0.21052632  0.78947368  0.31578947
   0.57894737]
 [ 0.73684211  0.94736842 -0.05263158  0.21052632  0.15789474  0.47368421
   0.47368421]
 [-0.05263158  0.31578947  0.52631579 -0.05263158  0.21052632  0.63157895
   0.52631579]]
[[0.47368421 0.21052632 0.15789474 0.78947368 0.73684211 0.78947368
  0.10526316]
 [0.10526316 0.31578947 0.15789474 0.26315789 0.84210526 0.36842105
  0.63157895]
 [0.78947368 1.         0.         0.26315789 0.21052632 0.52631579
  0.52631579]
 [0.         0.36842105 0.57894737 0.         0.26315789 0.68421053
  0.57894737]]
55.362442142665635


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [29]:
n = np.random.randint(0, 11, size = 80).reshape(8, 10)
s = n.sum(axis = 1)
mins = min(s)
ind = np.where(s == mins)
print(n,s,  mins, ind[0], sep = '\n')

[[ 6  4  3  4  1  4  4  4  0  6]
 [ 9  1  9  7 10  8  9  2  6  1]
 [ 9  7  2  4  8  1  8  0  2  5]
 [ 1  5  8  4  2  6  6  4  3 10]
 [ 8  2  4 10  3  4  8  4  8  9]
 [ 8  3  2  1  6  7  4  4  3 10]
 [ 2  5  7 10 10  0  8  7  6  4]
 [ 7 10  8  3  7  3  8  9 10  7]]
[36 62 46 49 60 48 59 72]
36
[0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [39]:
import math

point_1 = np.array((0, 0, 0))
point_2 = np.array((3, 3, 3))
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
distance = np.sqrt(sum_square)
distance_2 = math.dist(point_1, point_2)

print(distance, distance_2)

5.196152422706632 5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [38]:
'''-C = A*X*B'''
A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]
B = [[3, -1], [2, 1]]
C = [[7, 21], [11, 8], [8, 4]]
'''x = a^-1 *c * b^-1'''
invA = np.linalg.inv(A)
invB = np.linalg.inv(B)
x = invA @ C @ invB
print(x)

[[-1.00000000e+00 -5.32907052e-16]
 [ 2.00000000e+00 -1.00000000e+00]
 [-3.00000000e+00  4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

### Выведите на экран первые 5 строк массива

In [1]:
import numpy as np

with open('minutes_n_ingredients.csv') as f:
    array = np.loadtxt(f, delimiter=",", dtype='int32', skiprows=1)

print(array[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


### Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
result = {
    'avg': np.round(np.mean(array[:, 1:], axis=0), decimals=0),
    'min': np.min(array[:, 1:], axis=0),
    'max': np.max(array[:, 1:], axis=0),
    'median': np.median(array[:, 1:], axis=0)
}

# Выводим результат без скобок
for stat, values in result.items():
    print(f'{stat.capitalize()}: {", ".join(map(str, values))}')

Avg: 21601.0, 9.0
Min: 0, 1
Max: 2147483647, 39
Median: 40.0, 9.0


### Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  𝑞0.75

In [27]:
minutes_column_index = 1
q_75 = np.percentile(array[:, minutes_column_index], 75)
array[:, minutes_column_index] = np.minimum(array[:, minutes_column_index], q_75)
print("Измененный массив с ограничением сверху:")
print(array)

Измененный массив с ограничением сверху:
[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


### Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1

In [12]:
minutes_column_index = 1
zero_duration_indices = np.where(array[:, minutes_column_index] == 0)[0]
print(zero_duration_indices)
array[zero_duration_indices, minutes_column_index] = 1
print("Количество рецептов с продолжительностью 0:", len(zero_duration_indices))
print("Измененные данные:")
print(array)

[]
Количество рецептов с продолжительностью 0: 0
Измененные данные:
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


### Посчитайте, сколько уникальных рецептов находится в датасете

In [53]:
unique = np.unique(array[:, 0])
print(np.count_nonzero(unique))

100000


### Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [44]:
unique, counts = np.unique(array[:, 2], return_counts=True)
dict(zip(unique, counts))

{1: 13,
 2: 926,
 3: 2895,
 4: 5515,
 5: 7913,
 6: 9376,
 7: 10628,
 8: 10951,
 9: 10585,
 10: 9591,
 11: 8297,
 12: 6605,
 13: 4997,
 14: 3663,
 15: 2595,
 16: 1767,
 17: 1246,
 18: 790,
 19: 573,
 20: 376,
 21: 217,
 22: 161,
 23: 105,
 24: 69,
 25: 50,
 26: 28,
 27: 16,
 28: 16,
 29: 12,
 30: 12,
 31: 3,
 32: 1,
 33: 2,
 34: 1,
 35: 3,
 37: 1,
 39: 1}

### Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [15]:
filtered_data = array[array[:, 2] <= 5]
print(filtered_data)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


### Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [17]:
ingr_per_min = array[:, 2] / array[:,1]
print(max(ingr_per_min))

24.0


### Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [10]:
sorted_data = array[array[:, 1].argsort()[::-1]]

top_100_data = sorted_data[:100]

average_ingredients = np.mean(top_100_data[:, 2])

average_ingredients

6.61

### Выберите случайным образом и выведите информацию о 10 различных рецептах

In [19]:
random_indices = np.random.choice(len(array), 10, replace=False)
random_recipes = array[random_indices]

print("Информация о 10 случайных рецептах:")
print(random_recipes)

Информация о 10 случайных рецептах:
[[ 50592     10      8]
 [ 87900     45      9]
 [103011    125     11]
 [326565     30      7]
 [ 20165      5      5]
 [375957     25      9]
 [323574    120      7]
 [121738     15     10]
 [ 58122     23     14]
 [ 63300     20      5]]


### Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего

In [18]:
average_ingredients = np.mean(array[:, 2])
filtered_data = array[array[:, 2] < average_ingredients]
percentage_below_average = (len(filtered_data) / len(array)) * 100
percentage_below_average


58.802

### Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [21]:
minutes_column_index = 1
ingredients_column_index = 2
simple_recipe_column = np.logical_and(array[:, minutes_column_index] <= 20, array[:, ingredients_column_index] <= 5)
array = np.column_stack((array, simple_recipe_column.astype(int)))
print("Измененный массив с дополнительным столбцом:")
print(array)


Измененный массив с дополнительным столбцом:
[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


### Выведите процент "простых" рецептов в датасете

In [24]:
percent = np.mean(simple_recipe_column) * 100
percent

9.552

### Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [19]:
a = array[array[:, 1] < 10] 
b = array[((10 <= array[:, 1]) * (array[:, 1] < 20))] 
c = array[array[:, 1] >= 20] 
 
p = (min(len(a), len(b), len(c))) 
f = np.zeros((3, p, 3)) 
f[(0, np.arange(p))] = a[:,:] 
f[(1, np.arange(p))] = b[:p,:] 
f[(2, np.arange(p))] = c[:p,:] 
print(f) 
print(np.shape(f))

[[[6.76600e+04 5.00000e+00 6.00000e+00]
  [3.66174e+05 7.00000e+00 9.00000e+00]
  [2.04134e+05 5.00000e+00 3.00000e+00]
  ...
  [4.20725e+05 5.00000e+00 3.00000e+00]
  [4.74700e+03 1.00000e+00 9.00000e+00]
  [3.70915e+05 5.00000e+00 4.00000e+00]]

 [[9.47460e+04 1.00000e+01 6.00000e+00]
  [3.39410e+04 1.80000e+01 9.00000e+00]
  [4.46597e+05 1.50000e+01 5.00000e+00]
  ...
  [9.83100e+03 1.50000e+01 7.00000e+00]
  [3.35859e+05 1.20000e+01 1.40000e+01]
  [2.56812e+05 1.00000e+01 3.00000e+00]]

 [[1.27244e+05 6.00000e+01 1.60000e+01]
  [2.38910e+04 2.50000e+01 7.00000e+00]
  [1.57911e+05 6.00000e+01 1.40000e+01]
  ...
  [1.68901e+05 2.50000e+01 7.00000e+00]
  [3.92339e+05 3.50000e+01 1.30000e+01]
  [2.06732e+05 4.50000e+01 1.00000e+01]]]
(3, 7588, 3)
